spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/rs?serverTimezone=CET"
    username: "adnan"
    password: ""
    driver-class-name: "org.mariadb.jdbc.Driver"
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
      ddl-auto: "update"
      

  security:
    oauth2:
      resourceserver:
        jwt:
          #jwk-set-uri: https://seserver.se.hs-heilbronn.de:9443/TGEgypt-as-api/oauth2/jwks
          #issuer-uri: http://localhost:8088
          issuer-uri: https://seserver.se.hs-heilbronn.de:9443/TGEgypt-as-api


server:
  error:
    include-stacktrace: always
  #    whitelabel:
  #     enable: false
  #  ssl:
  #   enabled: true
  #   trust-store: "classpath:myTrustStore.jks"
  #   trust-store-password: "123456"
  #   trust-store-type: jks
  port: 8099
  servlet:
    session:
      #      timeout: 800
      cookie:
        http-only: true
        secure: true
#        max-age: 30m
#        samesite: STRICT
