# H2
#spring.datasource.url=jdbc:h2:file:C:/temp/test
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driverClassName=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/test
#spring.datasource.username=dbuser
#spring.datasource.password=dbpass
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

# Oracle
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
#spring.datasource.username=dbuser
#spring.datasource.password=dbpass
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect

# SQL Server
#spring.datasource.url=jdbc:sqlserver://localhost;databaseName=springbootdb
#spring.datasource.username=dbuser
#spring.datasource.password=dbpass
#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/as?serverTimezone=CET"
    username: adnan
    password: 
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

server:
#  error:
#    include-stacktrace: always
#    whitelabel:
#     enable: false
  ssl:
    enabled: true
  port: 8088
  servlet:
    session:
#      timeout: 800
      cookie:
        http-only: true
        secure: true
#        max-age: 30m
#        samesite: STRICT


#logging:
#  level:
#    org:
#      springframework:
#        security:
#          web:
#            FilterChainProxy: "DEBUG"

